# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 087579775d7fe8096aca38d0dbc644e09f7f7b938f285c0c143f5c3280a9750fabbbb41952ceefc09e62970c992ee48b60b234fb5e446ceb466a8b8300df0c99

test:
  secret_key_base: 360123a559aaebefb980d3ba13fd2ee41c730403397103011ead5f98dce181132a17ce899eb45042464888e9f8301bc6d11fc0bf87f477da0168a5918f04692e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
